version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: zonify-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: zonify
      POSTGRES_PASSWORD: zonify_secret
      POSTGRES_DB: zonify_db
    volumes:
      - zonify_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zonify -d zonify_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  zonify_pgdata:
